name: API Hunter.io

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout code"
          uses: actions/checkout@v4

        - name: "Node"
          uses: actions/setup-node@v4
          with: 
            node-version: "18"

        - name: "Install newman"
          run: "npm install -g newman"

        - name: "Install newman reporter"
          run: "npm install -g newman-reporter-html"

        - name: Run test Lead
          run: newman run -d lead_data.csv API_Hunter.postman_collection.json --env-var "token=$TOKEN_HUNTER" --folder crud_lead

        - name: Run test List Lead
          run: newman run -d list_lead_data.csv API_Hunter.postman_collection.json --env-var "token=$TOKEN_HUNTER" --folder crud_lista_de_lead
